#!/opt/perl5/bin/perl

##
##   TEST SET: platform
##
##   This test set performs basic checks of the custom "platform" Perl module
##
##   AUTHOR: Victor Burns
##     DATE: 2012-Apr-20
##
##   CHANGES:
##    2012-Apr-20 VICB - Original release
##

use strict;
use warnings;
use Data::Dumper;

use Test::More tests => 6;

BEGIN { use_ok( 'platform' ); }

## Class inst
my $platf;
my $cname = 'platform';

#-- Create instance (Check initial status)
#   (Tests assume this is UNIX/Linux, will fail on Windows)
ok( $platf = new platform, 'Create Property Instance' );
ok( ref $platf eq $cname, "Class == '$cname'" );
ok( ref $platf eq $cname && ( defined $platf->isUNIX   && $platf->isUNIX   == 1 || ! defined $platf->isUNIX   ), 'Check isUNIX' );
ok( ref $platf eq $cname && ( defined $platf->isWinTEL && $platf->isWinTEL == 1 || ! defined $platf->isWinTEL ), 'Check isWinTel' );
ok( ref $platf eq $cname &&
   (( ! defined $platf->isUNIX   && defined $platf->isWinTEL && $platf->isWinTEL == 1) ||
    ( ! defined $platf->isWinTEL && defined $platf->isUNIX   && $platf->isUNIX   == 1)),
   'Verify UNIX is not WinTel' );

## END
